# Netlify Configuration
[build]
  publish = "."
  command = "echo 'No build process needed - Static site ready!'"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdn.jsdelivr.net https://www.gstatic.com https://accounts.google.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; img-src 'self' data: https:; connect-src 'self' https: wss:; font-src 'self' https:;"

# Redirect all traffic to index-v2.html (main app)
[[redirects]]
  from = "/"
  to = "/index-v2.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/index-v2.html"
  status = 301

# Handle SPA routing (if needed in the future)
[[redirects]]
  from = "/*"
  to = "/index-v2.html"
  status = 200
  conditions = {Role = ["admin"]}

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
